### ISSUE TITLE
Very specific multivalue_form_element dependency (specific branch + 3 patches)

### ISSUE THREAD

**Issue by hans-langouche** [wieni/wmcontent_security_policy#6]
## Summary

The multivalue_form_element dependency is very specific and blocks installing other modules (e.g. wmimages)

**Comment by DieterHolvoet** [comment]
The specific branch was necessary before in order to make it compatible with Drupal 9. Looks like a Drupal 10 compatible release is out already, so that shouldn't be necessary anymore. The issues behind the patches haven't been fixed yet.

**Comment by hans-langouche** [comment]
Above pr seems to work fine, except that this patch causes a notice: https://www.drupal.org/project/multivalue_form_element/issues/3199298#comment-15057552

(I added a comment in the drupal issue)

**Comment by akasake** [comment]
I looked at the merge request, is there anything else you want me to review? @hans-langouche

**Comment by RobinHoutevelts** [comment]
Closing this.
The branch is merged upstream and the current `wmcontent_security_policy` release doesn't have that pinned anymore.

There is still the issue about [the warning that hans mentions](https://github.com/wieni/wmcontent_security_policy/issues/6#issuecomment-1554197917). But that's tracked on [d.org](https://www.drupal.org/project/multivalue_form_element/issues/3199298#comment-15057552)
